services:
  scraper:
    build: .
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.json:/app/config.json
      - ./feishu_config.json:/app/feishu_config.json
      - ./data:/app/data
      - ./log:/app/log
